import { Animal } from './types';

export const animals: Animal[] = [
  { id: 1, name: "Poes", imageUrl: "/animals/cat.jpg" },
  { id: 2, name: "Hond", imageUrl: "/animals/dog.jpg" },
  { id: 3, name: "Muis", imageUrl: "/animals/mouse.jpg" },
  { id: 4, name: "Paard", imageUrl: "/animals/horse.jpg" },
  { id: 5, name: "Koe", imageUrl: "/animals/cow.jpg" },
  { id: 6, name: "Varken", imageUrl: "/animals/pig.jpg" },
  { id: 7, name: "Kangoeroe", imageUrl: "/animals/kangaroo.jpg" },
  { id: 8, name: "Zeepaard", imageUrl: "/animals/seahorse.jpg" },
  { id: 9, name: "Olifant", imageUrl: "/animals/elephant.jpg" },
  { id: 10, name: "Giraffe", imageUrl: "/animals/giraffe.jpg" },
  { id: 11, name: "Leeuw", imageUrl: "/animals/lion.jpg" },
  { id: 12, name: "Mug", imageUrl: "/animals/mosquito.jpg" },
  { id: 13, name: "Bij", imageUrl: "/animals/bee.jpg" },
  { id: 14, name: "Schaap", imageUrl: "/animals/sheep.jpg" },
  { id: 15, name: "Stier", imageUrl: "/animals/bull.jpg" },
  { id: 16, name: "Ezel", imageUrl: "/animals/donkey.jpg" },
  { id: 17, name: "Tijger", imageUrl: "/animals/tiger.jpg" },
  { id: 18, name: "Schildpad", imageUrl: "/animals/turtle.jpg" },
  { id: 19, name: "Kikker", imageUrl: "/animals/frog.jpg" },
  { id: 20, name: "Zalm", imageUrl: "/animals/salmon.jpg" },
  { id: 21, name: "Krokodil", imageUrl: "/animals/crocodile.jpg" },
  { id: 22, name: "Flamingo", imageUrl: "/animals/flamingo.jpg" },
  { id: 23, name: "Kalkoen", imageUrl: "/animals/turkey.jpg" },
  { id: 24, name: "Kip", imageUrl: "/animals/chicken.jpg" },
  { id: 25, name: "Konijn", imageUrl: "/animals/rabbit.jpg" },
  { id: 26, name: "Koala", imageUrl: "/animals/koala.jpg" },
];